t = int(input('Digite um número para ver sua tabuada: '))
a = t * 1
b = t * 2
c = t * 3
d = t * 4
e = t * 5
f = t * 6
g = t * 7
h = t * 8
i = t * 9
j = t * 10

print('{} x 1 = {}' .format(t, a))
print('{} x 2 = {}' .format(t, b))
print('{} x 3 = {}' .format(t, c))
print('{} x 4 = {}' .format(t, d))
print('{} x 5 = {}' .format(t, e))
print('{} x 6 = {}' .format(t, f))
print('{} x 7 = {}' .format(t, g))
print('{} x 8 = {}' .format(t, h))
print('{} x 9 = {}' .format(t, i))
print('{} x 10 = {}' .format(t, j))
